export const ACTIVITY_TYPES = [
  'Ready Mix Concrete',
  'Reinforcement Steel',
  'Building Materials',
  'Plumbing',
  'Electrical',
  'Marble',
  'Ceramic',
  'Tiles',
  'Wood',
  'Scaffolding',
  'Gypsum',
  'Gypsum Board',
  'Aluminum',
  'Glass',
  'Paint',
  'HVAC',
  'Heavy Equipment',
  'Transportation',
  'Other',
];

export const ACTIVITY_KEYS = {
  'Ready Mix Concrete':  'readyMixConcrete',
  'Reinforcement Steel': 'reinforcementSteel',
  'Building Materials':  'buildingMaterials',
  'Plumbing':            'plumbing',
  'Electrical':          'electrical',
  'Marble':              'marble',
  'Ceramic':             'ceramic',
  'Tiles':               'tiles',
  'Wood':                'wood',
  'Scaffolding':         'scaffolding',
  'Gypsum':              'gypsum',
  'Gypsum Board':        'gypsumBoard',
  'Aluminum':            'aluminum',
  'Glass':               'glass',
  'Paint':               'paint',
  'HVAC':                'hvac',
  'Heavy Equipment':     'heavyEquipment',
  'Transportation':      'transportation',
  'Other':               'other',
};

export const STATUS_CONFIG = {
  new:          { label: 'New',          color: '#3b82f6', bg: 'rgba(59,130,246,0.12)'  },
  under_review: { label: 'Under Review', color: '#f59e0b', bg: 'rgba(245,158,11,0.12)'  },
  approved:     { label: 'Approved',     color: '#10b981', bg: 'rgba(16,185,129,0.12)'  },
  rejected:     { label: 'Rejected',     color: '#ef4444', bg: 'rgba(239,68,68,0.12)'   },
};
