export const ACTIVITY_TYPES = [
  'Ready Mix Concrete',
  'Reinforcement Steel',
  'Building Materials',
  'Plumbing',
  'Electrical',
  'Marble',
  'Ceramic',
  'Tiles',
  'Wood',
  'Scaffolding',
  'Gypsum',
  'Gypsum Board',
  'Aluminum',
  'Glass',
  'Paint',
  'HVAC',
  'Heavy Equipment',
  'Transportation',
  'Other',
];

export const COUNTRIES_KEYS = {
  // English keys
  'Saudi Arabia':         'saudiArabia',
  'United Arab Emirates': 'uae',
  'Kuwait':               'kuwait',
  'Qatar':                'qatar',
  'Bahrain':              'bahrain',
  'Oman':                 'oman',
  'Egypt':                'egypt',
  'Jordan':               'jordan',
  'Lebanon':              'lebanon',
  'Iraq':                 'iraq',
  'Other':                'other',
  // Arabic keys
  'المملكة العربية السعودية': 'saudiArabia',
  'سعودية': 'saudiArabia',
  'السعودية': 'saudiArabia',
  'الإمارات العربية المتحدة': 'uae',
  'الإمارات': 'uae',
  'الكويت': 'kuwait',
  'قطر': 'qatar',
  'البحرين': 'bahrain',
  'عُمان': 'oman',
  'عمان': 'oman',
  'مصر': 'egypt',
  'الأردن': 'jordan',
  'لبنان': 'lebanon',
  'العراق': 'iraq',
  'أخرى': 'other',
};

export const ACTIVITY_KEYS = {
  // English keys
  'Ready Mix Concrete':  'readyMixConcrete',
  'Reinforcement Steel': 'reinforcementSteel',
  'Building Materials':  'buildingMaterials',
  'Plumbing':            'plumbing',
  'Electrical':          'electrical',
  'Marble':              'marble',
  'Ceramic':             'ceramic',
  'Tiles':               'tiles',
  'Wood':                'wood',
  'Scaffolding':         'scaffolding',
  'Gypsum':              'gypsum',
  'Gypsum Board':        'gypsumBoard',
  'Aluminum':            'aluminum',
  'Glass':               'glass',
  'Paint':               'paint',
  'HVAC':                'hvac',
  'Heavy Equipment':     'heavyEquipment',
  'Transportation':      'transportation',
  'Other':               'other',
  // Arabic keys
  'خرسانة جاهزة': 'readyMixConcrete',
  'حديد تسليح': 'reinforcementSteel',
  'مواد بناء': 'buildingMaterials',
  'سباكة': 'plumbing',
  'كهرباء': 'electrical',
  'رخام': 'marble',
  'سيراميك': 'ceramic',
  'بلاط': 'tiles',
  'خشب': 'wood',
  'سقالات': 'scaffolding',
  'جبس': 'gypsum',
  'جبس بورد': 'gypsumBoard',
  'ألومنيوم': 'aluminum',
  'زجاج': 'glass',
  'دهانات': 'paint',
  'تكييف HVAC': 'hvac',
  'تكييف': 'hvac',
  'معدات ثقيلة': 'heavyEquipment',
  'نقل ولوجستيات': 'transportation',
  'نقل': 'transportation',
  'أخرى': 'other',
};

export const STATUS_CONFIG = {
  new:          { label: 'New',          color: '#3b82f6', bg: 'rgba(59,130,246,0.12)'  },
  under_review: { label: 'Under Review', color: '#f59e0b', bg: 'rgba(245,158,11,0.12)'  },
  approved:     { label: 'Approved',     color: '#10b981', bg: 'rgba(16,185,129,0.12)'  },
  rejected:     { label: 'Rejected',     color: '#ef4444', bg: 'rgba(239,68,68,0.12)'   },
};
